In [1]:
import pandas as pd 
df = pd.read_csv("C:/Users/emmlo/Downloads/Retail_Sales_Intelligence/data/retail_sales_dataset.csv")
df.head()

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
0,ORD-03903,2024-08-15,CUST32603,Aarav Mehta,39.0,Other,Central,Raipur,Groceries,Sugar,...,346.32,NaN,4043.14,289.18,56.04,Debit Card,NaN,True,Returned,7.0
1,ORD-02198,2022-08-16,CUST07881,Sanjay Verma,28.0,Male,West,Mumbai,Beauty,Sunscreen,...,858.66,0.08,9147.31,5355.56,64.49,Debit Card,5.0,False,Delivered,2.0
2,ORD-01348,2021-08-29,CUST49296,Pooja Sharma,41.0,Other,West,Surat,Furniture,Sofa,...,25941.32,0.14,110156.97,36956.51,67.65,Debit Card,4.0,False,Delivered,5.0
3,ORD-02076,2022-07-05,CUST05587,Priya Reddy,29.0,Other,West,Ahmedabad,Furniture,Bed Frame,...,22071.92,0.17,262066.11,66644.99,54.47,EMI,3.0,False,Delivered,4.0
4,ORD-00287,2020-05-07,CUST58035,Ritu Sharma,9.0,Male,Central,Nagpur,Groceries,Cooking Oil,...,320.06,0.31,323.95,31.38,48.81,Net Banking,4.0,False,Pending,4.0

In [2]:
#data frame information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4310 entries, 0 to 4309
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               4280 non-null   str
 1   order_date             4280 non-null   str
 2   customer_id            4280 non-null   str
 3   customer_name          4280 non-null   str
 4   age                    4150 non-null   float64
 5   gender                 4280 non-null   str
 6   region                 4280 non-null   str
 7   city                   4280 non-null   str
 8   product_category       4280 non-null   str
 9   product_name           4280 non-null   str
 10  quantity               4170 non-null   float64
 11  unit_price             4280 non-null   float64
 12  discount_pct           4143 non-null   float64
 13  sales_amount           4280 non-null   float64
 14  profit                 4280 non-null   float64
 15  shipping_cost          4280 non-null   float64
 16  payment_method         4280 non-null   str
 17  customer_satisfaction  3932 non-null   float64
 18  return_flag            4280 non-null   object
 19  order_status           4280 non-null   str
 20  days_to_ship           4180 non-null   float64
dtypes: float64(9), object(1), str(11)
memory usage: 707.2+ KB

In [3]:
#Number of null values within each column 
df.isnull().sum()

order_id                  30
order_date                30
customer_id               30
customer_name             30
age                      160
gender                    30
region                    30
city                      30
product_category          30
product_name              30
quantity                 140
unit_price                30
discount_pct             167
sales_amount              30
profit                    30
shipping_cost             30
payment_method            30
customer_satisfaction    378
return_flag               30
order_status              30
days_to_ship             130
dtype: int64

In [4]:
#Dropping rows where every single column is null 
df.dropna(how='all', inplace=True)

print(df.shape)
print(df.isnull().sum())

(4280, 21)
order_id                   0
order_date                 0
customer_id                0
customer_name              0
age                      130
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                 110
unit_price                 0
discount_pct             137
sales_amount               0
profit                     0
shipping_cost              0
payment_method             0
customer_satisfaction    348
return_flag                0
order_status               0
days_to_ship             100
dtype: int64

In [5]:
#filling in null values
df['age'] = df['age'].fillna(df['age'].median())
df['quantity']= df['quantity'].fillna(df['quantity'].median())
df['discount_pct']= df['discount_pct'].fillna(0)
df['days_to_ship']= df['days_to_ship'].fillna(df['days_to_ship'].median())
df['customer_satisfaction']= df['customer_satisfaction'].fillna(df['customer_satisfaction'].median())

print(df.isnull().sum())

order_id                 0
order_date               0
customer_id              0
customer_name            0
age                      0
gender                   0
region                   0
city                     0
product_category         0
product_name             0
quantity                 0
unit_price               0
discount_pct             0
sales_amount             0
profit                   0
shipping_cost            0
payment_method           0
customer_satisfaction    0
return_flag              0
order_status             0
days_to_ship             0
dtype: int64

In [6]:
#Changing column data types 
df['age'] = df['age'].astype(int)
df['quantity']= df['quantity'].astype(int)
df['days_to_ship']= df['days_to_ship'].astype(int)
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=True)
df['return_flag'] = df['return_flag'].astype(bool)
df['customer_satisfaction']= df['customer_satisfaction'].astype(int)

print(df.dtypes)

order_id                            str
order_date               datetime64[us]
customer_id                         str
customer_name                       str
age                               int64
gender                              str
region                              str
city                                str
product_category                    str
product_name                        str
quantity                          int64
unit_price                      float64
discount_pct                    float64
sales_amount                    float64
profit                          float64
shipping_cost                   float64
payment_method                      str
customer_satisfaction             int64
return_flag                        bool
order_status                        str
days_to_ship                      int64
dtype: object

In [7]:
#Checking for any spelling or formatting inconsistencies 
print(df['order_date'].unique())
print("\n")
print(df['region'].unique())
print("\n")
print(df['city'].unique())
print("\n")
print(df['product_category'].unique())
print("\n")
print(df['product_name'].unique())
print("\n")
print(df['payment_method'].unique())
print("\n")
print(df['order_status'].unique())
print("\n")

<DatetimeArray>
['2024-08-15 00:00:00', '2022-08-16 00:00:00', '2021-08-29 00:00:00',
 '2022-05-07 00:00:00', '2020-07-05 00:00:00', '2024-09-02 00:00:00',
 '2021-09-28 00:00:00', '2023-10-06 00:00:00', '2020-07-24 00:00:00',
 '2020-09-02 00:00:00',
 ...
 '2020-04-17 00:00:00', '2023-01-24 00:00:00', '2023-09-21 00:00:00',
 '2020-04-07 00:00:00', '2023-07-13 00:00:00', '2022-04-13 00:00:00',
 '2020-05-18 00:00:00', '2024-07-16 00:00:00', '2020-12-16 00:00:00',
 '2022-11-02 00:00:00']
Length: 1590, dtype: datetime64[us]


<StringArray>
['Central', 'West', 'North', 'East', 'South']
Length: 5, dtype: str


<StringArray>
[     'Raipur',      'Mumbai',       'Surat',   'Ahmedabad',      'Nagpur',
      'Bhopal',    'Amritsar',       'Patna',    'Ludhiana',        'Pune',
       'Kochi',   'Bangalore',    'Guwahati',       'Delhi',     'Chennai',
      'Indore',  'Chandigarh', 'Bhubaneswar',     'Kolkata',   'Hyderabad']
Length: 20, dtype: str


<StringArray>
[  'Groceries',      'Beauty',   'Furniture',       'Books',    'Clothing',
 'Electronics',      'Sports']
Length: 7, dtype: str


<StringArray>
[         'Sugar',      'Sunscreen',           'Sofa',      'Bed Frame',
    'Cooking Oil', 'Self-Help Book',          'Saree',          'Kurta',
       'Wardrobe',      'Dal (1kg)',       'Lipstick',      'Cook Book',
        'T-Shirt',          'Chair',          'Dress',         'Tablet',
         'Jacket',     'Headphones',      'Dumbbells',     'Comic Book',
       'Football',         'Laptop',    'Cricket Bat',       'Hair Oil',
      'Bookshelf',         'Camera',          'Jeans',  'Tennis Racket',
           'Desk',     'Face Cream',  'Fiction Novel',          'Cycle',
       'Textbook',     'Smartwatch',     'Rice (5kg)',            'Tea',
          'Flour',        'Perfume',       'Yoga Mat',     'Smartphone',
      'Biography',        'Shampoo']
Length: 42, dtype: str


<StringArray>
['Debit Card', 'EMI', 'Net Banking', 'Cash on Delivery', 'Credit Card', 'UPI']
Length: 6, dtype: str


<StringArray>
[ 'Returned', 'Delivered',   'Pending', 'Cancelled',   'Shipped', 'delivered',
 'cancelled',   'shipped',   'pending']
Length: 9, dtype: str

In [8]:
#Checking return flag for its unique values 
print(df['return_flag'].unique())

[ True False]

In [9]:
#Checking the count for each customer satisfaction rating and the median 
print(df['customer_satisfaction'].value_counts())
print(df['customer_satisfaction'].median())

customer_satisfaction
3    1115
4     824
5     786
2     779
1     776
Name: count, dtype: int64
3.0

In [10]:
#Capitalizing order status values to reduce spelling inconsistency
df['order_status']= df['order_status'].str.capitalize()
print(df['order_status'].unique())

<StringArray>
['Returned', 'Delivered', 'Pending', 'Cancelled', 'Shipped']
Length: 5, dtype: str

In [11]:
#dropping all duplicate rows
df = df.drop_duplicates()
print(df.duplicated().sum())
print(df.shape)

0
(4200, 21)

In [12]:
#Checking the number of customers associated with different order quantities
df['quantity'].value_counts().sort_index(ascending=False).head(10)

quantity
999      8
10     406
9      432
8      432
7      395
6      359
5      480
4      420
3      417
2      426
Name: count, dtype: int64

In [13]:
#checking the product category, sale amount, and unit price associated with quantity == 999
df[df['quantity'] == 999][['product_name', 'unit_price', 'sales_amount']]

        product_name  unit_price  sales_amount
242        Cook Book      403.63     203951.50
1012  Self-Help Book      545.25     729651.06
1112          Jacket     2567.40    2281458.22
1138   Tennis Racket     9380.72    7936261.20
1700      Rice (5kg)      195.29     140042.31
2178   Fiction Novel      709.64     533420.31
2582           Jeans     3280.13    2586345.13
3865          Tablet    18619.45   17360314.17

In [14]:
df = df[df['quantity'] != 999]
print(df.shape)

(4192, 21)

In [15]:
df.to_csv("C:/Users/emmlo/Downloads/Retail_Sales_Intelligence/data/retail_sales_cleaned.csv", index=False)

In [22]:
#Transfering dataframe to postgre for connection to powerBI (utilised this route to be able to clean the file additionally and update postgre without having to manually add an updated csv file)
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine

print(os.getcwd())

load_dotenv()

password = os.getenv("db_password")

engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/Retail_sales')

df.to_sql(
    name="retail_sales_cleaned",
    con= engine,
    if_exists= "replace",
    index= False,
    method= "multi",
    chunksize= 1000
)

C:\Users\emmlo\Downloads\Retail_Sales_Intelligence\notebooks

4192